### ISSUE TITLE
Custom confing.yaml

### ISSUE THREAD

**Issue by whottel** [andersen-lab/Freyja#93]
Hello, 

I have noticed on recent runs that the lineage grouping rules I have in my config.yaml file are not consistenly followed when running freyja dashboard. (I am still using version 1.3.10)
For example I have the following:
```
Lineages:
  grp_1:
    name: "BA.2"
    members:
      - "BA.2*"
    color: "orange"
  grp_2:
    name: "BA.4.6"
    members:
      - "BA.4.6*"
    color: "olive"
  grp_3:
    name: "BA.4"
    members:
      - "BA.4*"
    color: "green"   
  grp_4:
    name: "BA.5"
    members:
      - "BA.5*"      
    color: "red"  
```
In this case the BA.5 sublineages BA.5.2.3 and BA.5.3.2 are grouped correctly, but BA.5.2.17, BA.5.1.10, and BA.5.5.3 are still showing up individually. 
Additionally, how can I write these rules so that BE and BF can also be grouped under BA.5?

Thanks,
Wes
